---
- name: perform-basic-setup-on-centos
  hosts: webservers
  become: yes
  gather_facts: yes

  tasks:
  - name: centos-set-timezone
    timezone:
      name: UTC


  - name: set-Hostname
    hostname:
      name: "{{ inventory_hostname }}"
    register: hostname_task_result

  - name: debug-show-hostname-host_task_result
    debug:
      var: hostname_task_result

#  - name: update-os
#    dnf:
#      name: '*'
#      state: latest
#    register: update_task_result

  - name: debug-update-os-result
    debug:
      var: update_task_result

  - name: install-dnf-automatic
    dnf:
      name: dnf-automatic
      state: installed
    register: dnf_automatic_result

  - name: copy-dnf-configuration-file
    copy:
      src: automactic.conf
      dest: /etc/dnf/
      mode: 0644
    when: dnf_automatic_result is changed

  - name: start-dnf-service
    service:
      name: dnf-automatic
      state: started
      enabled: yes
    when: dnf_automatic_result is changed

  - name: reboot-if-required
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
    when: (hostname_task_result is changed) # or (update_task_result is changed)

  - name: pause
    pause:
      seconds: 30
    when: (hostname_task_result is changed) #or (update_task_result is changed)

  - name: try-reconnect
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300
    when: (hostname_task_result is changed) #or (update_task_result is changed)
