---
  ## https://ansible-tips-and-tricks.readthedocs.io/en/latest/os-dependent-tasks/variables/
- name: Importing RHEL8 Tasks if required.
  import_tasks: rhel8.yml
  when: ansible_facts['os_family']|lower == 'redhat' and ansible_distribution_major_version == '8'
- name: Importing RHEL7 Tasks if required.
  import_tasks: rhel7.yml
  when: ansible_facts['os_family']|lower == 'redhat' and ansible_distribution_major_version == '7'
- name: Importing Debian tasks if required.
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
